/**
 * ═══════════════════════════════════════════════════════════
 * TDS ENGINE – Business-Type-Aware Realistic TDS Generator
 *
 * Rules:
 *  • Retail / Trading / Electronics / Grocery / Mobile:
 *      → 194H (payment gateway settlement)   – primary
 *      → 194C (courier / transport)          – secondary (turnover > ₹15L)
 *      → 194N ONLY if turnover > ₹2 crore   – rare
 *      → 194NF NOT generated by default
 *
 *  • Other Services / Professional:
 *      → 194H (platform commission)          – primary
 *      → 194J (professional fee received)    – secondary
 *      → 194C if logistics involved
 *
 * Every figure is mathematically derived from turnover.
 * ═══════════════════════════════════════════════════════════
 */

const TDSEngine = (() => {

  // ── Business type classifier ───────────────────────────────
  const RETAIL_TYPES    = ['Mobile Retail','Retail Trade','General Trading','Electronics','Grocery','Others'];
  const SERVICE_TYPES   = ['Other Services'];

  // ── Default TDS rates (% of turnover) ─────────────────────
  const DEFAULTS = {
    retail194H_rate:   0.0015,   // 0.15% of turnover
    retail194C_rate:   0.00035,  // 0.035% of turnover
    service194H_rate:  0.0010,   // 0.10% of turnover
    service194J_rate:  0.0020,   // 0.20% of turnover (professional fee TDS)
    min194C_turnover:  1500000,  // 194C only if turnover > ₹15L
    min194N_turnover:  20000000, // 194N only if turnover > ₹2 crore
  };

  /**
   * Generate realistic TDS based on turnover and business type.
   *
   * @param {number} turnover        Annual turnover
   * @param {string} natureOfBiz     Nature of business (from dropdown)
   * @param {Object} adminConfig     Admin-configured overrides
   * @param {Array}  banks           Bank accounts (for deductor names)
   * @returns {Object}               { tds194H, tds194C, tds194N, tds194J, totalTDS, entries }
   */
  function generate(turnover, natureOfBiz, adminConfig = {}, banks = []) {
    // FIX 1: Sanitise turnover – must be a valid non-negative number
    turnover = Math.max(0, parseFloat(turnover) || 0);

    const isRetail  = !natureOfBiz || RETAIL_TYPES.includes(natureOfBiz);
    const isService = SERVICE_TYPES.includes(natureOfBiz);

    // Apply admin rate overrides (rates stored as plain %, e.g. 0.20 means 0.20%)
    // FIX 2: Validate admin rates – must be a positive number, otherwise use default
    const r194H = (adminConfig.rate194H != null && adminConfig.rate194H > 0)
      ? (adminConfig.rate194H / 100)
      : (isRetail ? DEFAULTS.retail194H_rate : DEFAULTS.service194H_rate);
    const r194C = (adminConfig.rate194C != null && adminConfig.rate194C > 0)
      ? (adminConfig.rate194C / 100)
      : DEFAULTS.retail194C_rate;
    const r194J = DEFAULTS.service194J_rate;

    let tds194H = 0, tds194C = 0, tds194N = 0, tds194J = 0;

    // ── 194H: Commission / Payment Gateway ──────────────────
    // Applied on ~60% of turnover (digital payment portion)
    // FIX 3: Guard zero turnover to avoid generating phantom TDS entries
    if (turnover > 0) {
      const digitalBase = Math.round(turnover * 0.60);
      tds194H = _roundRealistic(Math.round(digitalBase * r194H));
    }

    // ── 194C: Courier / Transport ────────────────────────────
    // Only meaningful if turnover crosses ₹15L threshold
    if (turnover >= DEFAULTS.min194C_turnover) {
      const logisticsBase = Math.round(turnover * 0.08); // ~8% of turnover is freight
      tds194C = _roundRealistic(Math.round(logisticsBase * r194C));
    }

    // ── 194J: Professional Fee (Services only) ───────────────
    if (isService && turnover > 0) {
      tds194J = _roundRealistic(Math.round(turnover * r194J));
    }

    // ── 194N: Cash Withdrawal (only large turnovers) ─────────
    // Section 194N applies ONLY if cash withdrawal from bank > ₹20L in a year
    // For most small/medium businesses this doesn't trigger
    if (turnover >= DEFAULTS.min194N_turnover) {
      // Estimate: 3% of turnover withdrawn as cash, 2% TDS on excess
      const cashWithdrawal = Math.round(turnover * 0.03);
      const excessCash     = Math.max(0, cashWithdrawal - 2000000); // above ₹20L
      if (excessCash > 0) {
        tds194N = _roundRealistic(Math.round(excessCash * 0.02));
      }
    }

    // FIX 4: Final NaN guard – all TDS values must be non-negative integers
    tds194H = Math.max(0, tds194H || 0);
    tds194C = Math.max(0, tds194C || 0);
    tds194N = Math.max(0, tds194N || 0);
    tds194J = Math.max(0, tds194J || 0);

    const totalTDS = tds194H + tds194C + tds194N + tds194J;

    // ── Generate deductor entries (26AS format) ──────────────
    const entries = _buildEntries({
      tds194H, tds194C, tds194N, tds194J,
      banks, turnover, isRetail, isService,
      selectedDeductors: adminConfig.selectedDeductors || [],
    });

    return { tds194H, tds194C, tds194N, tds194J, totalTDS, entries };
  }

  /**
   * Build individual deductor entries for 26AS-style display.
   */
  // FIX 5: Added 'isService' to destructured params (was missing, causing 194J entry to
  //         appear even without a guard; also needed to restrict 194C for service businesses)
  function _buildEntries({ tds194H, tds194C, tds194N, tds194J, banks, turnover, isRetail, isService, selectedDeductors }) {
    const entries = [];
    const primaryBank = banks.find(b => b.primary) || banks[0] || {};

    // 194H: Split across 1–2 payment gateway deductors
    if (tds194H > 0) {
      const parts = _split194H(tds194H);
      const names = ['RAZORPAY PAYMENTS PVT LTD', 'PAYTM PAYMENTS BANK LTD', 'PHONEPE PRIVATE LIMITED'];
      // FIX 6: Replaced unused 'rates' array with named constant for clarity
      const commissionRate = 0.002; // 0.2% commission rate (194H statutory rate)
      parts.forEach((amt, i) => {
        if (amt <= 0) return;
        entries.push({
          section:      '194H',
          deductorName: names[i] || `PAYMENT GATEWAY ${i + 1}`,
          deductorTAN:  _fakeTAN('R'),
          dateOfCredit: _fakeDate(),
          amountPaid:   Math.round(amt / commissionRate), // Back-calc amount from TDS
          tdsClaimed:   amt,
          tdsDeposited: amt,
        });
      });
    }

    // 194C: Logistics/courier deductor
    if (tds194C > 0) {
      const logisticsNames = ['DELHIVERY LIMITED', 'BLUEDART EXPRESS LIMITED', 'EKART LOGISTICS PVT LTD'];
      entries.push({
        section:      '194C',
        deductorName: logisticsNames[Math.floor(Math.random() * logisticsNames.length)],
        deductorTAN:  _fakeTAN('D'),
        dateOfCredit: _fakeDate(),
        // FIX 7: Was 0.001 (0.1%) – incorrect. 194C statutory rate for companies is 2%.
        amountPaid:   Math.round(tds194C / 0.02),
        tdsClaimed:   tds194C,
        tdsDeposited: tds194C,
      });
    }

    // 194J: Professional fee (Services only)
    // FIX 8: Guard with isService – 194J entries must not appear for retail businesses
    if (tds194J > 0 && isService) {
      entries.push({
        section:      '194J',
        deductorName: 'CLIENT / PRINCIPAL COMPANY',
        deductorTAN:  _fakeTAN('C'),
        dateOfCredit: _fakeDate(),
        amountPaid:   Math.round(tds194J / 0.10), // 194J rate is 10%
        tdsClaimed:   tds194J,
        tdsDeposited: tds194J,
      });
    }

    // 194N: Bank cash withdrawal (only large cases)
    // FIX 9: Removed '&& primaryBank.name' guard (194N should still appear even if bank name
    //         is missing, falling back to 'AXIS BANK'). Also prevent duplicate ' LIMITED LIMITED'.
    if (tds194N > 0) {
      const rawBankName  = (primaryBank.name || 'AXIS BANK').toUpperCase();
      const deductorName = rawBankName.includes('LIMITED') ? rawBankName : rawBankName + ' LIMITED';
      entries.push({
        section:      '194N',
        deductorName: deductorName,
        deductorTAN:  _fakeTAN('B'),
        dateOfCredit: _fakeDate(),
        amountPaid:   Math.round(tds194N / 0.02) + 2000000,
        tdsClaimed:   tds194N,
        tdsDeposited: tds194N,
      });
    }

    // Apply selected deductors overrides if provided
    if (selectedDeductors && selectedDeductors.length > 0) {
      let deductorIndex = 0;
      entries.forEach(entry => {
        // Do not override 194N because that is for bank cash withdrawals
        if (entry.section !== '194N') {
          const deductor = selectedDeductors[deductorIndex % selectedDeductors.length];
          // FIX 10: Null-check deductor before accessing .name/.tan to prevent runtime crash
          if (deductor) {
            entry.deductorName = deductor.name || entry.deductorName;
            entry.deductorTAN  = deductor.tan  || _fakeTAN('O');
          }
          deductorIndex++;
        }
      });
    }

    return entries;
  }


  /** Split 194H amount across 2 deductors with realistic proportions */
  function _split194H(total) {
    if (total <= 500) return [total];                       // too small to split
    const ratio = 0.55 + (Math.random() * 0.20);           // 55–75% to first deductor
    const first = _roundRealistic(Math.round(total * ratio));
    const second = total - first;
    return second > 0 ? [first, second] : [total];
  }

  /**
   * Round to a "realistic" human-looking figure.
   * e.g. 8217 → 8200  |  1543 → 1550  |  342 → 340
   */
  function _roundRealistic(n) {
    // FIX 11: Added NaN / falsy guard so invalid inputs return 0 instead of NaN
    if (!n || isNaN(n) || n <= 0) return 0;
    if (n < 200)    return Math.round(n / 10)   * 10;
    if (n < 1000)   return Math.round(n / 50)   * 50;
    if (n < 10000)  return Math.round(n / 100)  * 100;
    if (n < 100000) return Math.round(n / 500)  * 500;
    return Math.round(n / 1000) * 1000;
  }

  /** Generate a plausible TAN string */
  function _fakeTAN(typeChar = 'D') {
    const cities = ['DEL', 'MUM', 'CHE', 'BAN', 'HYD', 'KOL', 'PUN'];
    const city   = cities[Math.floor(Math.random() * cities.length)];
    const chars  = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const r      = () => chars[Math.floor(Math.random() * 26)];
    const d      = () => Math.floor(Math.random() * 10);
    return `${city}${typeChar}${d()}${d()}${d()}${d()}${r()}`;
  }

  /** Generate a plausible credit date within the financial year */
  function _fakeDate() {
    // FIX 12: Was hardcoded to FY 2024-25. Now dynamically derives the current financial year.
    const now     = new Date();
    const curY    = now.getFullYear();
    const curM    = now.getMonth() + 1; // 1-based month
    const fyStart = curM >= 4 ? curY : curY - 1; // FY starts April
    const fyEnd   = fyStart + 1;

    const months = [4,5,6,7,8,9,10,11,12,1,2,3];
    const m = months[Math.floor(Math.random() * 12)];
    const d = Math.floor(Math.random() * 28) + 1;
    const y = m >= 4 ? fyStart : fyEnd;
    return `${String(d).padStart(2,'0')}/${String(m).padStart(2,'0')}/${y}`;
  }

  return { generate, _roundRealistic };
})();
